# -*- coding: utf-8 -*-
"""Project-107

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V98ix92z8MnqN3OH8ghLa3W9m-NT40nQ
"""

import csv
import pandas as pd
import plotly.graph_objects as go

df = pd.read_csv("data.csv")

studentdf = df.loc[df['student_id']=="TRL_xsl"]

print(studentdf.groupby("level")["attempt"].mean())

fig = go.Figure(go.Scatter(
    x = studentdf.groupby("level")["attempt"].mean(),
    y = ['Level 1','Level 2','Level 3','Level 4'],
))

fig.show()